### ISSUE TITLE
Problema com os endpoints messages/:id/parrot e messages/:id/unparrot

### ISSUE THREAD

**Issue by bartier** [tagview/tagchatter#2]
Não estou conseguindo o retorno de uma **mensagem** com os endpoints:
`https://tagchatter.herokuapp.com/messages/:id/parrot`
`https://tagchatter.herokuapp.com/messages/:id/unparrot`

Eu passo como parâmetro o **id de uma mensagem** que eu consigo pelo endpoint `/messages`, mas retorna:
```
{
  "type": "message_not_found",
  "error": "Message not found",
  "message": ":id"
}
```

**Comment by viniciusvgv** [comment]
Opa, verdade. Obrigado por reportar! O @Igormandello resolveu, agora está funcionando
